HopBarWebSite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('main/', views.main, name='main'),
    path('product/<int:id>', views.product, name='product'),
    path('checkout/', views.Checkout.as_view(), name='checkout'),
    path('order/<int:id>', views.order, name='order'),
    path('cart/', views.cart, name='cart'),
    path('about_us/', views.about_us, name='about_us'),
    path('orders_list/', views.orders_list, name='orders_list'),
    path("add-to-cart", views.add_to_cart, name="add_to_cart"),
    path("delete-from-cart", views.delete_from_cart, name="delete_from_cart")
]

users/urls.py
from django.urls import path, include
from users.views import Register, MyLoginView

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', Register.as_view(), name='register'),
    path('auth/', MyLoginView.as_view(), name='auth')
]

products/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
from datetime import datetime
from django import forms
from django.forms import ModelForm
from django.forms.widgets import TextInput, EmailInput, RadioSelect

class Product(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=256)
    image = models.ImageField(upload_to="media")
    price = models.DecimalField(decimal_places=0, max_digits=6)
    class Meta:
        db_table = "gallery"
    def __str__(self):
        return f'{self.name}-{self.id}'

class Cart(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)

    @property
    def total_price(self):
        cartRows = self.cartRows.all()
        total = sum([item.price for item in cartRows])
        return total

    @property
    def num_of_items(self):
        cartRows = self.cartRows.all()
        quantity = sum([item.quantity for item in cartRows])
        return quantity

class CartProduct(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='items')
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name="cartRows")
    quantity = models.IntegerField(default=0)

    def __str__(self):
        return self.product.name

    @property
    def price(self):
        new_price = self.product.price * self.quantity
        return new_price

class Order(models.Model):
    id = models.AutoField(primary_key=True)
    create_date = models.DateTimeField(default=datetime.now(), blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    firstname = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)
    email = models.EmailField()
    delivery_address = models.CharField(max_length=256)
    is_kaspi_pay = models.BooleanField()
    is_cash_pay = models.BooleanField()
    completed = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)

    @property
    def total_price(self):
        orderRows = self.orderRows.all()
        total = sum([item.price for item in orderRows])
        return total

    @property
    def order_number(self):
        return str(self.id).zfill(5)

    @property
    def num_of_items(self):
        orderRows = self.orderRows.all()
        quantity = sum([item.quantity for item in orderRows])
        return quantity

class OrderProduct(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='order_products')
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name="orderRows")
    quantity = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.order.id}-{self.product.name}'

    @property
    def price(self):
        new_price = self.product.price * self.quantity
        return new_price

class OrderForm(forms.Form):
    CHOICES = [
        ('1', 'Kaspi Gold'),
        ('2', 'Наличные'),
    ]
    firstname = forms.CharField(widget=TextInput(attrs={'class': 'form-control'}), max_length=100)
    lastname = forms.CharField(widget=TextInput(attrs={'class': 'form-control'}), max_length=100)
    email = forms.EmailField(widget=EmailInput(attrs={'class': 'form-control'}))
    delivery_address = forms.CharField(widget=TextInput(attrs={'class': 'form-control'}), max_length=256)
    pay_method = forms.ChoiceField(widget=forms.RadioSelect(attrs={'class': 'hop-text-contrast-color'}), choices=CHOICES)

products/forms.py
from django import forms
from .models import *


class ProductAddForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = [""]

products/views.py
from django.shortcuts import render
from django.views import View
from django.shortcuts import redirect
from .forms import *
import json
from django.http import JsonResponse

def main(request):
    form = ProductAddForm(request.POST or None)
    products = Product.objects.all()

    if request.user.is_authenticated:
        cart, created = Cart.objects.get_or_create(user=request.user, completed=False)
        orders = Order.objects.all().filter(user=request.user)

    return render(request, 'landing/main.html', locals())

def product(request, id):
    cart = None
    orders = []
    product = Product.objects.get(id=id)

    if request.user.is_authenticated:
        cart, created = Cart.objects.get_or_create(user=request.user, completed=False)
        orders = Order.objects.all().filter(user=request.user)

    context = {
        "cart": cart,
        "orders": orders,
        "product": product
    }

    return render(request, 'landing/product.html', context)

def cart(request):
    cart = None
    cartRows = []
    orders = []

    if request.user.is_authenticated:
        cart, created = Cart.objects.get_or_create(user=request.user, completed=False)
        cartRows = cart.cartRows.all()
        orders = Order.objects.all().filter(user=request.user)

    context = {
        "cart": cart,
        "cartRows": cartRows,
        "orders": orders
    }

    return render(request, "landing/cart.html", context)

def add_to_cart(request):
    data = json.loads(request.body)
    product_id = data["id"]
    product = Product.objects.get(id=product_id)

    if request.user.is_authenticated:
        cart, created = Cart.objects.get_or_create(user=request.user, completed=False)
        cartProduct, created = CartProduct.objects.get_or_create(cart=cart, product=product)
        cartProduct.quantity += 1
        cartProduct.save()

        num_of_item = cart.num_of_items

    return JsonResponse(num_of_item, safe=False)

def delete_from_cart(request):
    data = json.loads(request.body)
    product_id = data["id"]
    product = Product.objects.get(id=product_id)

    if request.user.is_authenticated:
        cart = Cart.objects.get(user=request.user)
        cartProduct = CartProduct.objects.get(cart=cart, product=product)
        cartProduct.quantity -= 1
        cartProduct.delete()

        num_of_item = cart.num_of_items

    return JsonResponse(num_of_item, safe=False)

def orders_list(request):
    orders = Order.objects.all().filter(user=request.user)
    cart, created = Cart.objects.get_or_create(user=request.user, completed=False)

    context = {
        "orders": orders,
        "cart": cart
    }

    return render(request, "landing/orders_list.html", context)

def order(request, id):
    orders = Order.objects.all().filter(user=request.user)
    cart, created = Cart.objects.get_or_create(user=request.user, completed=False)
    order = Order.objects.get(id=id)
    orderRows = order.orderRows.all()

    print(order)

    context = {
        "orders": orders,
        "cart": cart,
        "order": order,
        "orderRows": orderRows
    }

    return render(request, "landing/order.html", context)

def about_us(request):
    cart = None
    orders = []

    if request.user.is_authenticated:
        cart, created = Cart.objects.get_or_create(user=request.user, completed=False)
        orders = Order.objects.all().filter(user=request.user)

    context = {
        "cart": cart,
        "orders": orders
    }

    return render(request, 'landing/about_us.html', context)
class Checkout(View):
    template_name = 'landing/checkout.html'

    def get(self, request):
        cart = None
        cartRows = []
        orders = []
        form = OrderForm()

        if request.user.is_authenticated:
            cart, created = Cart.objects.get_or_create(user=request.user, completed=False)
            cartRows = cart.cartRows.all()
            orders = Order.objects.all().filter(user=request.user)

        context = {
            "cart": cart,
            "cartRows": cartRows,
            "form": form,
            "orders": orders
        }

        return render(request, self.template_name, context)

    def post(self, request):
        form = OrderForm(request.POST)
        cart, created = Cart.objects.get_or_create(user=request.user, completed=False)
        cartRows = cart.cartRows.all()


        if form.is_valid():
            order = Order(
                firstname=form.data.get("firstname"),
                lastname=form.data.get("lastname"),
                email=form.data.get("email"),
                delivery_address=form.data.get("delivery_address"),
                is_kaspi_pay=form.data.get("pay_method") == '1',
                is_cash_pay=form.data.get("pay_method") == '2',
                user=request.user,
                completed=False
            )
            order.save()

            for cartRow in cartRows:
                print(cartRow.product)
                orderProduct, created = OrderProduct.objects.get_or_create(
                    order=order,
                    product=cartRow.product,
                    quantity=cartRow.quantity,
                )
                orderProduct.save()

                cartProduct = CartProduct.objects.get(cart=cart, product=cartRow.product)
                cartProduct.delete()

            return redirect('main')



        context = {
            "cart": cart,
            "cartRows": cartRows,
            "form": form
        }

        return render(request, self.template_name, context)

templates/landing/about_us.html
{% extends "landing/base.html" %}
{% block content %}
{% load static %}
<div class="container mt-5">
  <div class="row bg-hop-light pt-3">
    <h1 class="hop-text-contrast-color">THE HOP BAR</h1>
    <div class="g-1 p-3">
      <p class="hop-text-contrast-color">
        Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
        Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
        Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
        Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
        Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum Lorem ipsum
      </p>
    </div>
  </div>
</div>
<div class="container marketing">
  <div class="row bg-hop-light pt-5 hop-text-contrast-color mt-5">
    <div class="col-lg-4">
      <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-color)"></rect></svg>
      <h2 class="fw-normal">Heading</h2>
      <p>Some representative placeholder content for the three columns of text below the carousel. This is the first column.</p>
    </div>
    <div class="col-lg-4">
      <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-color)"></rect></svg>
      <h2 class="fw-normal">Heading</h2>
      <p>Some representative placeholder content for the three columns of text below the carousel. This is the first column.</p>
    </div>
    <div class="col-lg-4">
      <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-color)"></rect></svg>
      <h2 class="fw-normal">Heading</h2>
      <p>Some representative placeholder content for the three columns of text below the carousel. This is the first column.</p>
    </div>
  </div>

  <div class="row featurette bg-hop-light pt-3 pb-3 hop-text-contrast-color mt-5">
    <div class="col-md-7">
      <h2 class="featurette-heading fw-normal lh-1">First featurette heading</h2>
      <p class="lead">Some great placeholder content for the first featurette here. Imagine some exciting prose here.</p>
    </div>
    <div class="col-md-5">
      <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-bg)"></rect><text x="50%" y="50%" fill="var(--bs-secondary-color)" dy=".3em">500x500</text></svg>
    </div>
  </div>

  <div class="row featurette bg-hop-light pt-3 pb-3 hop-text-contrast-color mt-5">
    <div class="col-md-7 order-md-2">
      <h2 class="featurette-heading fw-normal lh-1">Oh yeah, it’s that good. <span class="text-body-secondary">See for yourself.</span></h2>
      <p class="lead">Another featurette? Of course. More placeholder content here to give you an idea of how this layout would work with some actual real-world content in place.</p>
    </div>
    <div class="col-md-5 order-md-1">
      <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-bg)"></rect><text x="50%" y="50%" fill="var(--bs-secondary-color)" dy=".3em">500x500</text></svg>
    </div>
  </div>
</div>

{% endblock %}

templates/landing/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Hop Bar</title>
        <link rel="icon" href="{% static 'images/logo.png' %}" type="image/png">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
        <style type="text/css">
            html, body {
                margin: 0px;
                padding: 0px;
            }
        </style>
    </head>

    <body>
        {% include "landing/header.html" %}

        <div class="container-fluid">
            {% block content %}
            {% endblock %}
        </div>
        {% include "landing/footer.html" %}
    </body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="{% static 'js/add_to_cart.js' %}"></script>
    <script src="{% static 'js/delete_from_cart.js' %}"></script>
    <script src="{% static 'js/generate_csrftoken.js' %}"></script>
</html>

templates/landing/cart.html
{% extends "landing/base.html" %}
{% block content %}
{% load static %}

<div class="container mt-5">
  <div class="row g-5 bg-hop-light mt-5" id="cart-container">
    {% if cartRows %}
      <h2 class="hop-text-contrast-color">Корзина</h2>
      <table class="table table-dark table-stripped text-center">
        <thead>
          <tr>
            <th>#</th>
            <th>Действия</th>
            <th>Наименование</th>
            <th>Цена</th>
            <th>Количсетво</th>
            <th>Общая цена</th>
          </tr>
        </thead>
        <tbody>
          {% for cartRow in cartRows %}
            <tr id="product-tr-{{ cartRow.product.id }}">
              <th>{{ forloop.counter }}</th>
              <td><button class="btn btn-sm btn-hop delete-from-cart-btn" value="{{ cartRow.product.id }}">Удалить</button></td>
              <td>{{ cartRow.product.name }}</td>
              <td>{{ cartRow.product.price }}</td>
              <td>{{ cartRow.quantity }}</td>
              <td>{{ cartRow.price }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
      <div class="d-flex justify-content-between align-items-center mb-5">
        <a href="{% url 'checkout' %}" class="btn btn-lg btn-hop">Оформить заказ</a>
        <h3 class="hop-text-contrast-color">Общая сумма заказа: {{ cart.total_price }} тенге</h3>
      </div>
    {% else %}
      <h2 class="hop-text-contrast-color mb-5 text-center">В корзине пусто)</h2>
    {% endif %}

  </div>
</div>

{% endblock %}

templates/landing/checkout.html
{% extends "landing/base.html" %}
{% block content %}
{% load static %}
<div class="container mt-5">
  {% if form.errors %}
      {% for field in form %}
          {% for error in field.errors %}
              <p>{{ error }}</p>
          {% endfor %}
      {% endfor %}
  {% endif %}
  <form action="{% url 'checkout' %}" method="POST">
    <div class="row g-5 bg-hop-light mt-5">
      <div class="col-md-5 col-lg-4 order-md-last">
        <h4 class="d-flex justify-content-between align-items-center mb-3">
          <span class="hop-text-contrast-color">Корзина</span>
          <span class="badge hop-contrast-background-color rounded-pill">{{ cart.num_of_items }}</span>
        </h4>
        <ul class="list-group mb-3">
          {% for cartRow in cartRows %}
            <li class="list-group-item d-flex justify-content-between lh-sm">
              <div>
                <h6 class="my-0">{{ cartRow.product.name }} x {{ cartRow.quantity }}</h6>
                <small class="text-muted">{{ cartRow.product.description }}</small>
              </div>
              <span class="text-muted">{{ cartRow.price }} Тенге</span>
            </li>
          {% endfor %}
          <li class="list-group-item d-flex justify-content-between">
            <span>Всего (Тенге)</span>
            <strong>{{ cart.total_price }}</strong>
          </li>
        </ul>
        <div class="input-group mb-4">
          <button class="w-100 btn btn-hop btn-lg" type="submit">Оформить заказ</button>
        </div>
      </div>
      <div class="col-md-7 col-lg-8">
        <h4 class="mb-3 hop-text-contrast-color">Адрес доставки</h4>

          <div class="row g-3">
            <div class="col-sm-6">
              <label for="id_firstname" class="form-label hop-text-contrast-color">Имя</label>
              {{ form.firstname }}
            </div>

            <div class="col-sm-6">
              <label for="id_lastname" class="form-label hop-text-contrast-color">Фамилия</label>
              {{ form.lastname }}
            </div>

            <div class="col-6">
              <label for="id_email" class="form-label hop-text-contrast-color">Email</label>
              {{ form.email }}
            </div>

            <div class="col-6">
              <label for="id_delivery_address" class="form-label hop-text-contrast-color">Адрес</label>
              {{ form.delivery_address }}
            </div>
          </div>
          <h4 class="mb-3 hop-text-contrast-color">Оплата</h4>
          <div class="my-3">
            <div class="form-check">
              {{ form.pay_method }}
            </div>
          </div>
      </div>
      {% csrf_token %}
    </div>
  </form>
</div>

{% endblock %}

templates/landing/footer.html
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 mt-4 border-top hop-main-background-color fixed-bottom">
    <p class="col-md-4 mb-0 text-muted hop-text-contrast-color">© 2022 Company, Inc</p>

    <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
    </a>

    <ul class="nav col-md-4 justify-content-end">
        <li><a href="{% url 'main' %}" class="nav-link px-2 hop-link">Главная</a></li>
        {% if not user.is_superuser and user.is_authenticated %}
            <li>
                <a href="{% url 'cart' %}" class="nav-link px-2 hop-link">
                    Корзина
                    {% if cart.num_of_items != 0 %}
                        <span class="badge hop-contrast-background-color rounded-pill" id="num_of_items">
                            {{ cart.num_of_items }}
                        </span>
                    {% endif %}
                </a>
            </li>
            <li>
                <a href="{% url 'orders_list' %}" class="nav-link px-2 hop-link">
                    Заказы
                    {% if orders|length != 0 %}
                        <span class="badge hop-contrast-background-color rounded-pill">
                            {{ orders|length }}
                        </span>
                    {% endif %}
                </a>
            </li>
        {% endif %}
        <li><a href="{% url 'about_us' %}" class="nav-link px-2 hop-link">О нас</a></li>
    </ul>
  </footer>

templates/landing/header.html
{% load static %}

<header class="p-3 text-bg-dark">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="{% url 'main' %}" class="d-flex align-items-center mb-2 mb-lg-0 text-decoration-none">
                <img class="rounded" height="40px" src="{% static 'images/logo.png' %}"/>
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'main' %}" class="nav-link px-2 hop-link">Главная</a></li>
<!--                <li><a href="{% url 'orders_list' %}" class="nav-link px-2 hop-link">Заказы</a></li>-->
                {% if not user.is_superuser and user.is_authenticated %}
                    <li>
                        <a href="{% url 'cart' %}" class="nav-link px-2 hop-link">
                            Корзина
                            {% if cart.num_of_items != 0 %}
                                <span class="badge hop-contrast-background-color rounded-pill" id="num_of_items">
                                    {{ cart.num_of_items }}
                                </span>
                            {% endif %}
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'orders_list' %}" class="nav-link px-2 hop-link">
                            Заказы
                            {% if orders|length != 0 %}
                                <span class="badge hop-contrast-background-color rounded-pill">
                                    {{ orders|length }}
                                </span>
                            {% endif %}
                        </a>
                    </li>
                {% endif %}
                <li><a href="{% url 'about_us' %}" class="nav-link px-2 hop-link">О нас</a></li>
            </ul>

            <div class="text-end">
                {% if user.is_authenticated %}
                    User: {{ user }}
                    <a class="btn btn-hop" href="/users/logout">Выйти</a>
                {% else %}
                    <a class="btn btn-hop" href="/users/auth">Авторизация</a>
                    <a class="btn btn-hop" href="/users/register">Регистрация</a>
                {% endif %}
            </div>
        </div>
    </div>
</header>

templates/landing/landing.html
<h1>Hello World!!!</h1>
<h1>How are you {{ name }}?</h1>
<h1>Today is {{ today }}</h1>

templates/landing/order.html
{% extends "landing/base.html" %}
{% block content %}
{% load static %}
<div class="container mt-5">
  <h4 class="hop-text-contrast-color"> Заказ №{{ order.order_number }}</h4>
  <div class="row g-5 bg-hop-light">
    <div class="col-md-5 col-lg-4 order-md-last">
      <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="hop-text-contrast-color">Продукты</span>
        <span class="badge hop-contrast-background-color rounded-pill">{{ order.num_of_items }}</span>
      </h4>
      <ul class="list-group mb-3">
        {% for orderRow in orderRows %}
          <li class="list-group-item d-flex justify-content-between lh-sm">
            <div>
              <h6 class="my-0">{{ orderRow.product.name }} x {{ orderRow.quantity }}</h6>
              <small class="text-muted">{{ orderRow.product.description }}</small>
            </div>
            <span class="text-muted">{{ orderRow.price }} Тенге</span>
          </li>
        {% endfor %}
        <li class="list-group-item d-flex justify-content-between">
          <span>Всего (Тенге)</span>
          <strong>{{ order.total_price }}</strong>
        </li>
      </ul>
    </div>
    <div class="col-md-7 col-lg-8">
      <h4 class="mb-3 hop-text-contrast-color">Адрес доставки</h4>

        <div class="row g-3">
          <div class="col-sm-6">
            <label for="id_firstname" class="form-label hop-text-contrast-color">Имя</label>
            <input class="form-control" type="text" value="{{ order.firstname }}" disabled/>
          </div>

          <div class="col-sm-6">
            <label for="id_lastname" class="form-label hop-text-contrast-color">Фамилия</label>
            <input class="form-control" type="text" value="{{ order.lastname }}" disabled/>
          </div>

          <div class="col-6">
            <label for="id_email" class="form-label hop-text-contrast-color">Email</label>
            <input class="form-control" type="text" value="{{ order.email }}" disabled/>
          </div>

          <div class="col-6">
            <label for="id_delivery_address" class="form-label hop-text-contrast-color">Адрес</label>
            <input class="form-control" type="text" value="{{ order.delivery_address }}" disabled/>
          </div>
        </div>
        <h4 class="mb-3 hop-text-contrast-color">Оплата</h4>
        <div class="my-3">
          <div class="form-check">
            <div id="id_pay_method" class="hop-text-contrast-color">
              <div>
                <label for="id_pay_method_0">
                  <input type="radio" name="pay_method" value="1" class="hop-text-contrast-color" checked="{{ order.is_kaspi_pay }}" {% if order.is_kaspi_pay is True %}disabled{% endif %} />
                  Kaspi Gold
                </label>
              </div>
              <div>
                  <label for="id_pay_method_1">
                    <input type="radio" name="pay_method" value="2" class="hop-text-contrast-color" checked="{{ order.is_cash_pay }}" {% if order.is_cash_pay is True %}disabled{% endif %} />
                    Наличные
                  </label>
              </div>
            </div>
          </div>
        </div>
    </div>
  </div>
</div>

{% endblock %}

templates/landing/product.html
{% extends "landing/base.html" %}
{% block content %}
{% load static %}
<div class="container mt-5">
  {% if form.errors %}
      {% for field in form %}
          {% for error in field.errors %}
              <p>{{ error }}</p>
          {% endfor %}
      {% endfor %}
  {% endif %}
  <form action="{% url 'checkout' %}" method="POST">
    <div class="row g-5 bg-hop-light mt-5">
      <div class="col-md-5 col-lg-4 mt-3 mb-3">
        <img class="bd-placeholder-img card-img-top" height="280" src="{{ product.image.url }}"/>
      </div>
      <div class="col-md-7 col-lg-8 flex-vertical-direction mt-5 mb-5">
          <h2 class="hop-text-contrast-color">{{ product.name }}</h2>
          <p class="card-text hop-text-contrast-color">{{ product.description }}</p>
          <div class="d-flex justify-content-between align-items-center">
            <button type="button" class="btn btn-hop add-to-cart-btn" value="{{ product.id }}">В корзину</button>
            <h3 class="hop-text-contrast-color">{{ product.price }} тенге</h3>
          </div>
      </div>
      {% csrf_token %}
    </div>
  </form>
</div>

{% endblock %}